apiVersion: v1
kind: ConfigMap
metadata:
  name: soulnotes-backend-config
data:
  URL: "postgresql://postgres:5432/soulnotes"
  REDIS_HOSTS: "redis://redis:6379"
  ORIGINS: "http://localhost:5173"
  VOICE_STORAGE_DIR: "/data/voice_uploads"
