apiVersion: v1
kind: ConfigMap
metadata:
  name: soulnotes-backend-config
data:
  SOULNOTES_DB_URL: "postgresql://postgres:5432/soulnotes"
  SOULNOTES_REDIS_HOSTS: "redis://redis:6379"
  SOULNOTES_CORS_ORIGINS: "http://localhost:5173"
  SOULNOTES_VOICE_DIR: "/data/voice_uploads"
