package kurvcygnus.soulnotes.config.prelaunch;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

class ConfigWriterTest
{
    //* JetBrains 注解为 compileOnly 依赖, 不在 test 编译类路径上, 故测试源不使用 (与既有测试保持一致).
    @TempDir Path dir;

    //* 测试夹具: 按简报参数顺序 (envName, key, defaultValue, group), 其余元数据字段与本任务无关, 填中性值.
    private static PropertyMetaParser.ConfigItemMeta meta(String envName, String key, String defaultValue, String group)
    {
        return new PropertyMetaParser.ConfigItemMeta(
            key, envName, defaultValue, group, key, "", PropertyMetaParser.InputType.TEXT, "", 0, false);
    }

    @Test void writesBothFilesGroupedAndAligned() throws Exception
    {
        final var items = List.of(
            meta("SOULNOTES_DB_URL", "quarkus.datasource.reactive.url", "db", "数据库"),
            meta("SOULNOTES_REDIS_HOSTS", "quarkus.redis.hosts", "rd", "缓存"));
        final var written = ConfigWriter.write(dir, items, Map.of("SOULNOTES_DB_URL", "postgresql://h:1/d"), "2026-09-13T00:00:00Z");
        final var props = Files.readString(written.propertiesFile());
        assertTrue(props.contains("# Generated by soulnotes setup @ 2026-09-13T00:00:00Z"));
        assertTrue(props.contains("# ---- 数据库 ----"));
        assertTrue(props.contains("quarkus.datasource.reactive.url = postgresql://h:1/d\n"));//* 行尾 \n 同时钉死换行符约定.
        assertFalse(props.contains("quarkus.redis.hosts"));//* 未显式设置项不写.
        assertFalse(props.contains("# ---- 缓存 ----"));//* 全组无显式值时, 空分组节整体不落盘.
        final var env = Files.readString(written.envFile());
        assertTrue(env.contains("# Generated by soulnotes setup @ 2026-09-13T00:00:00Z"));//* 头部行双文件一致.
        assertTrue(env.contains("SOULNOTES_DB_URL=postgresql://h:1/d"));
    }

    @Test void existingFileBackedUpToBak() throws Exception
    {
        Files.createDirectories(dir.resolve("config"));
        Files.writeString(dir.resolve("config/application.properties"), "old");
        Files.writeString(dir.resolve(".env"), "old-env");
        ConfigWriter.write(dir, List.of(), Map.of(), "t");
        assertEquals("old", Files.readString(dir.resolve("config/application.properties.bak")));
        assertEquals("old-env", Files.readString(dir.resolve(".env.bak")));//* .env 同为落盘目标, 备份规则一致.
    }

    @Test void alignsWholeFileColumnAndKeepsFirstEncounterGroupOrder() throws Exception
    {
        final var items = List.of(
            meta("SOULNOTES_DB_URL", "quarkus.datasource.reactive.url", "db", "数据库"),
            meta("SOULNOTES_JWT_SECRET", "jwt.secret", "jwt", "安全"),
            meta("SOULNOTES_REDIS_HOSTS", "quarkus.redis.hosts", "rd", "缓存"));
        final var written = ConfigWriter.write(dir, items,
            Map.of("SOULNOTES_DB_URL", "pg://d", "SOULNOTES_JWT_SECRET", "s3cret", "NO_SUCH_ENV", "x"), "t");
        final var props = Files.readString(written.propertiesFile());
        //* 对齐选型: 键列宽 = 整份文件已写出键的最大长度 (31), 短键补空格至同一 " = " 列; 组按条目首次出现顺序.
        assertTrue(props.contains("quarkus.datasource.reactive.url = pg://d\n"));
        assertTrue(props.contains("jwt.secret" + " ".repeat(22) + "= s3cret"));//* 31 - 10 = 21 补位 + 1 个 " = " 前导空格.
        assertTrue(props.indexOf("# ---- 数据库 ----") < props.indexOf("# ---- 安全 ----"));
        assertFalse(props.contains("quarkus.redis.hosts"));//* 未显式项整项跳过.
        assertFalse(props.contains("# ---- 缓存 ----"));
        final var env = Files.readString(written.envFile());
        assertTrue(env.contains("SOULNOTES_JWT_SECRET=s3cret"));//* .env 行严格 envName=value, 不做任何键补齐.
        assertTrue(env.contains("SOULNOTES_DB_URL=pg://d"));//* 无补位: 键内空格会破坏 source/kubectl 等消费方解析.
        assertFalse(env.contains("SOULNOTES_REDIS_HOSTS"));
        assertFalse(env.contains("NO_SUCH_ENV"));//* 匹配不到任何条目的显式值静默忽略.
    }
}
